sudo: required
services:
- docker
env:
  COMPOSE_VERSION: 1.27.4
  global:
  - secure: "i1gZc69hJ8uWKzalEECZtVnBi9pDgFQibbUsaQgRASrICjAau4iRl1LuCyYbwD2DWZrcrtjKKZzJB2jDCzRlj/xpFI3VEPlWd49N7t40bDlkJ5i9jvHdGKkILgZuYBu337g8byEdLnAodXUlsHeg4GjGOPMbcLBeEM2Igr0gVP0GGkSdfPJhovASYrrM2GX0JNwNhiE3yyv4KEBI+wfeKliBweVqtXNS/BG2wiTJslNq4y+6hf7lGIOpJ9zLOK29rpVREHSLEtIO1EnjG1OsDqgMtYH7fE9m4r/8NkKaVl+m4C66PH2CEoY6cra84VgnyKRMA3h7IBUiSDXLhTNu4Mh1GpS+fJ9XS437fDE19t+I0k/pfaUuFg1j5awblVj9ntUzOQf+hcrSfvBFswx60qy0QNRahw2Us9qVbQ90Gj9WeYaw1XD72AGnkVAgapR+gvicJ6dylfrrFpwriTH6sCgpeHeTgeo+2JTGL3CxIL3+usqtL1Lawe+c20YZKFl1TqMw1exYM14b90Hy/phsUhZDxyt7HjVU93anVwbzmSr5ITxRJCuxREdH+MDnJBLUtoMYejW/ev1fwYHHpuxTZWy0Z3KHnBQV3PBtXZJEVfsLG1k3TpZN4TMzixY0SUTdo2GniKx2FGU6btgo/4lagqLDuprRROuwYUGto3f/4BE="
  - secure: "IPWco1QseSVQrj3+PvSJV+Igh8/s0sNEnudLum3usgMak6tVIG8g6D1VDb/md7mxRFsZY6WA4ZamftUDWmZGTs405Tdrl9E7T+CmbnQ+1fHGhx69a6fslqM+hJXPeX9DIqAF0+qsNUNSKRb73t62XMsVLLLLRZdhujMYsUBtNqwnon+2sMRj2fGhLMy2CGtGjgcHg2KWBYukWPLGv2kXH61blLNBRPZKGAtn3Zyq/rWqDH5vR5yENTwBiv8ja9YdBssrTEFb1BSEYokhRFqkGvwhIndjlRTmcfds0uYZGyCW76ft6YdNX/DWpfWksmM+15nBotLi45iBG7BrE3b45vJymVUlvXzn1dPW3N/4VF/Wzsu/OlKcqdGCt3rtMa+BcK4ydhdZ7v12WphFhzGt389UkpXKaQCFb7R8giKOEA6xldLwi068wnOIWn2Q0/r14fJKGNnVeOLfd1CnDMYinlcPWE+TNhll5jcSFMXEL4A1nDRLWARDt9gNFwI6gd3VcBOpSpfvVYoH2veztUC1N1/AR83vZ6jZeRL58MRX+AxJrELdC1DgmrmFL2Kdi2W2gHEz5vPaLoNxbBKO0BXgKbN8aTmuCYmCVsfXipfznXRq2G/GyWcxr7O0bR9e7gVFBpn5oJJu6QNiJIrtYB6NsIKezp4HN4fKmI9VPrc5B1U="
before_install:
- curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
script:
- docker-compose build 
- docker-compose up -d
- docker-compose run web rails db:migrate
- docker-compose run web bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: PUTUOtU+9vnkTkpP4ZM0EZPoaBvG16suy+8XV2wS83Byqgwv0UFtEEV8BtGDrvgzuhJaG2T3f1gU1xNWjBzOvp7YLOpD29TmYaigYYzctkDqhr+tCVOeRGX+QLrnCpwB1nnLHCV5VD0Bsl7GZO9MMrHYEQ4aZqEwNDAM0VbcrZBNMrUPuzdgRpBRBNgXynNLXublTp0aNfVQ7Aen5XmOHuCm1wPr74OXxKe5kEPKneZcKHQeSUE2u3oyrrP3Vj2e+vinhQmYwZZnx3z3eLkolVkPmn5q2zcs4jGIUvoGTDRheOEqAinpWRJ2TCiVLHhoyV0yLy/vVSTVpt0U0v4uexBctBIzU29D/4bgl6K1emDlIJKQ+MQLBivl9rWsdsy07Kj0BZbEQ0FNNnmi6fmJw49DYafBnFaL8H4r1FumJD13nUCe5OIeamFAMM15L0d9+uw/mxHGOlHamLyAn4MWho/p/wXE+FkJyRNOC9zIn7QSXMpGlZqT7DdZIbrgJjpCmiovML8ea/HNjPrOsUeSzK+dk6m80KqFQ0KAIyrNYBEvgBWpphKvfJ1b7uZxZ04PvrZwEfBwNeGbYxBwqMYfkeNwof7vzjKlh5O4cL0h8/5ZYZrR3Ro+VF5V38NOa0Gal4eObo+AwVouHOEKsXESHT8luKq7e6BfpsYzQiCTS3k=
  app: shop-melcado
