default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>
  database: <%= ENV.fetch("POSTGRES_DB") %>
  username: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  min_messages: debug5

test:
  <<: *default

production:
  <<: *default
