default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= Rails.application.credentials.postgres_password %>
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test