default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>
  database: <%= Rails.application.credentials.POSTGRES_DB %>
  username: <%= Rails.application.credentials.PGUSER %>
  password: <%= Rails.application.credentials.PGPASSWORD %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
