default:
  navigation:
    - title: Tech
      subtitle: Categories
      url: /t/tech
      items:
        - :title: Bluetooth earphones
          :url: /t/tech/bluetooth-earphones
      promo_banners:
        - subtitle: New arrivals
          title: Tech items 2021
          url: /t/new-arrivals/2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Women
      subtitle: Categories
      url: /t/women
      items:
        - :title: Dresses
          :url: /t/women/dresses
        - :title: Tops and T-shirts
          :url: /t/women/tops-and-t-shirts
        - :title: Jackets and Coats
          :url: /t/women/jackets-and-coats
      promo_banners:
        - subtitle: New collection
          title: Spring/Summer 2021
          url: /t/new-collection/spring-summer-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Men
      subtitle: Categories
      url: /t/men
      items:
        - :title: Shirts
          :url: /t/men/shirts
        - :title: T-shirts
          :url: /t/men/t-shirts
        - :title: Jackets and Coats
          :url: /t/men/jackets-and-coats
      promo_banners:
        - subtitle: New collection
          title: Spring/summer 2021
          url: /t/new-collection/spring-summer-2021
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Sportswear
      subtitle: Categories
      url: /t/sportswear
      items:
        - :title: Tops
          :url: /t/sportswear/tops
        - :title: Sweatshirts
          :url: /t/sportswear/sweatshirts
        - :title: Hats
          :url: /t/sportswear/hats
      promo_banners:
        - subtitle: New collection
          title: The best 2021 sportswear equipment 
          url: /t/new-collection/sportswear
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
